### ISSUE TITLE
cURL command not working on Windows

### ISSUE THREAD

**Issue by IvaWonderbush** [IvaWonderbush/Y.A.T.E.S#10]
May need to provide download link for cURL if it cannot be solved with an other command native to Windows. Not really the best option though.

**Comment by IvaWonderbush** [comment]
cURL command for Windows that works without installing 3rd party software:
`powershell curl http://thomasyates.nl/docs/version.html`

Now all that needs to be done is an OS check and Windows version check to see if PowerShell is supported or not.

**Comment by VADemon** [comment]
Please use "Invoke-WebRequest" instead of this weird alias. More: https://github.com/PowerShell/PowerShell/pull/1901#issuecomment-240900165 (in short: what will happen with a real curl.exe?)

**Comment by IvaWonderbush** [comment]
I've been messing around with this for a few days now. I've decided I'm not going to support Windows with this issue or any other regarding finding solutions to Unix tools and commands. The reason for this is that Windows 7 does not have most of PowerShell thus most of its commands. Invoke-WebRequest is unknown on some versions of Windows yet weirdly enough known on other (sometimes older) versions which is just confusing and crap. Spending too much time on this issue only to (currently) check for updates is a waste of time.

The solution to make sure it works for everyone is that Windows users may install Git and make sure the Windows terminal can use Unix tools and commands (this is an installer option). Yes, this will override native Windows commands but honestly if you're not using Unix based commands then why even bother.
