### ISSUE TITLE
"Command not found" always displays for third party commands

### ISSUE THREAD

**Issue by GeoB99** [IvaWonderbush/Y.A.T.E.S#24]
If you implement a plugin which provides say commands (which begin with the initial command prefix `!`), Y.A.T.E.S thinks it is a built-in command which however it isn't and it'll display `Command not found` every time you execute a third party command from a plugin.

**Comment by IvaWonderbush** [comment]
Are you trying to register it via your own custom command function, or are you using the built in commands? If the latter, do not forget to give your group the permission to use the command.

**Comment by GeoB99** [comment]
Yes, I'm registering it via my own custom command function. For instance:
```Lua
if ( Command[1] == '!movect' ) then

  -- Code here
end
```
Due to the `!` prefix of the command, Y.A.T.E.S thinks it is a built-in command which it isn't thus the message will be displayed every time a third party command is executed.

**Comment by IvaWonderbush** [comment]
You shouldn't be creating your own command function though. I don't feel like making exceptions for this as it would be against implementing a single standard in a framework.
