### ISSUE TITLE
Some console LUA ERROR while using !kick & !ban (commands work)

### ISSUE THREAD

**Issue by irfan-dahir** [IvaWonderbush/Y.A.T.E.S#4]
`Player has left the game (kicked: ayy lmao)
LUA ERROR: sys/lua/yates/yates_functions.lua:168: attempt to concatenate a boolean value
 -> sys/lua/yates/yates_functions.lua:168: in function 'executeSayCommand'
 -> sys/lua/yates/yates_hooks.lua:31: in function <sys/lua/yates/yates_hooks.lua:16>
 -> in Lua hook 'say', params: 3
: !kick 1 ayy lmao
`
`Player has left the game (banned)
LUA ERROR: sys/lua/yates/yates_functions.lua:168: attempt to concatenate a boolean value
 -> sys/lua/yates/yates_functions.lua:168: in function 'executeSayCommand'
 -> sys/lua/yates/yates_hooks.lua:31: in function <sys/lua/yates/yates_hooks.lua:16>
 -> in Lua hook 'say', params: 3
Player: !ban 1
`

**Comment by IvaWonderbush** [comment]
Fixed!
