### ISSUE TITLE
executeSayCommand's 3rd param has no use

### ISSUE THREAD

**Issue by irfan-dahir** [IvaWonderbush/Y.A.T.E.S#6]
Plus, what's `func = loadstring("yates.func.say.".._tbl[1]:sub(#yates.setting.say_prefix+1).."()")`

The +1 in the prefix makes toTable("help") call the "elp" command.

Shouldn't `func = loadstring("yates.func.say."..txt.."()")` be enough?

**Comment by IvaWonderbush** [comment]
Removed.
